# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96ebcbf51e0ab8d0ee9a77b3f0fd114ca5c3c9fd3af03568f0c1ef9622cc63dc7d85d00090753c1fd9d40cc2f1015bce0e59a29b3b39f2b86158085318df716

test:
  secret_key_base: 1af40b0318eb96d9927908abeeb216b0d7f1f270ad9275e97b8041e4b44948e4f19b878a040ffc6130eb271587f1832fe6fd9f8c19bf22c4de8053cf7e17ba70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
